version: '3.2'

services:
  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    restart: on-failure
    environment:
      POSTGRES_USER: que_locks
      POSTGRES_DB: que_locks_test
      POSTGRES_HOST_AUTH_METHOD: trust # don't require password
